generic-service:
  nameOverride: probation-search-ui
  productId: "UNASSIGNED" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  serviceAccountName: probation-search-ui

  image:
    repository: ghcr.io/ministryofjustice/probation-search-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: probation-search-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    AUDIT_SERVICE_NAME: "probation-search-ui"
    AUDIT_SQS_REGION: "eu-west-2"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    probation-search-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      AUTH_CODE_CLIENT_ID: "API_CLIENT_ID"
      AUTH_CODE_CLIENT_SECRET: "API_CLIENT_SECRET"
      DELIUS_AUTH_SECRET: "DELIUS_AUTH_SECRET"
      CLIENT_CREDS_CLIENT_ID: "SYSTEM_CLIENT_ID"
      CLIENT_CREDS_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      SENTRY_DSN: "SENTRY_DSN"
      SENTRY_LOADER_SCRIPT_ID: "SENTRY_LOADER_SCRIPT_ID"
      SIGNING_SECRET: "SIGNING_SECRET"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - moj_cloud_platform
      - digital_staff_and_mojo
      - unilink_staff
      - probation
      - prisons
      - private_prisons

generic-prometheus-alerts:
  targetApplication: probation-search-ui
  alertSeverity: probation-integration-notifications
