---
# Per environment values which override defaults in probation-search-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-search-dev.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: dev
    INGRESS_URL: "https://probation-search-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SENTRY_TRACES_SAMPLE_RATE: "1.0"

generic-prometheus-alerts:
  businessHoursOnly: true
