---
# Per environment values which override defaults in probation-search-ui/values.yaml

generic-service:
  ingress:
    host: probation-search.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod
    INGRESS_URL: "https://probation-search.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    DELIUS_URL: "https://ndelius.probation.service.justice.gov.uk"
